[workspace]
members = ["states-derive"]

[package]
name = "state-set"
version = "0.1.0"
authors = ["Taihei OKI <t.oki.natrium@gmail.com"]
edition = "2021"

[dependencies]
states-derive = { path = "./states-derive", optional = true }

[features]
derive = ["states-derive"]

[[test]]
name = "derive_states"
path = "tests/derive_states.rs"
required-features = ["derive"]
